# Defines a default set of lint rules from the Effective
# Dart guide. For details and rationale, see
# https://dart.dev/guides/language/effective-dart
include: package:effective_dart/analysis_options.1.2.0.yaml

# For lint rules and documentation, see
# http://dart-lang.github.io/linter/lints.
linter:
  rules:
    - prefer_expression_function_bodies
    - prefer_typing_uninitialized_variables
    - use_function_type_syntax_for_parameters
